{
    "name": "Portail Client – Gestion de Parc",
    "version": "1.0.0",
    "category": "Website",
    "summary": "Portail client : équipements, contrats, factures et tickets d’intervention",
    "description": "Tableau de bord dédié aux clients créés dans le module parc_client.",
    "author": "Dev SYLLA",
    "license": "LGPL-3",
    "depends": [
        "portal",
        "website",
        "mail",
        "account",
        # Modules fonctionnels
        "parc_client",
        "parc_equipement",
        "parc_contrat",
        "parc_facturation",
        "parc_intervention",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rule_portal.xml",
        "views/portal_templates.xml",
        "views/portal_home_inherit.xml",
        "report/facture_report.xml",
    ],
    "installable": True,
    "application": False,
}
